# proxy.conf

host "auth.local" {
    proxy_pass http://127.0.0.1:9001;
    proxy_pass http://127.0.0.1:9002;
    proxy_pass http://127.0.0.1:9003;
    dist_policy round-robin;
}

host "p2p.local" {
    proxy_pass http://127.0.0.1:9004;
    proxy_pass http://127.0.0.1:9005;
    proxy_pass http://127.0.0.1:9006;
    dist_policy round-robin;
}

